// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATQA1mQDP4r4KE2u5QoFEttPLvx8WK-rg',
    appId: '1:554602506203:web:bcb0eae5ca2da51e3ee9fe',
    messagingSenderId: '554602506203',
    projectId: 'nippo-e8922',
    authDomain: 'nippo-e8922.firebaseapp.com',
    databaseURL: 'https://nippo-e8922.firebaseio.com',
    storageBucket: 'nippo-e8922.appspot.com',
    measurementId: 'G-FXTJM2Q755',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSPm7SNLRYk1bBp5DFku-n-A4PrmjQFuU',
    appId: '1:554602506203:android:052255c36e16460d3ee9fe',
    messagingSenderId: '554602506203',
    projectId: 'nippo-e8922',
    databaseURL: 'https://nippo-e8922.firebaseio.com',
    storageBucket: 'nippo-e8922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALpm4NWeHM-PkaBkMaVuOWUJhRG0DHE-I',
    appId: '1:554602506203:ios:28faf2e71f77493b3ee9fe',
    messagingSenderId: '554602506203',
    projectId: 'nippo-e8922',
    databaseURL: 'https://nippo-e8922.firebaseio.com',
    storageBucket: 'nippo-e8922.appspot.com',
    androidClientId: '554602506203-cvqnsumv3q5c3mk5oj800tr7lugoo81u.apps.googleusercontent.com',
    iosClientId: '554602506203-2e3jkpfh6rabqmci2cck8k7ufkr9665e.apps.googleusercontent.com',
    iosBundleId: 'com.htsuruo.nippo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALpm4NWeHM-PkaBkMaVuOWUJhRG0DHE-I',
    appId: '1:554602506203:ios:28faf2e71f77493b3ee9fe',
    messagingSenderId: '554602506203',
    projectId: 'nippo-e8922',
    databaseURL: 'https://nippo-e8922.firebaseio.com',
    storageBucket: 'nippo-e8922.appspot.com',
    androidClientId: '554602506203-cvqnsumv3q5c3mk5oj800tr7lugoo81u.apps.googleusercontent.com',
    iosClientId: '554602506203-2e3jkpfh6rabqmci2cck8k7ufkr9665e.apps.googleusercontent.com',
    iosBundleId: 'com.htsuruo.nippo',
  );
}
